name: Telegram Notifications

on: 
  workflow_run:
    workflows: ["Pylint", "PyTest", "Publish Docker image"]
    types:
      - completed

jobs:
  messages:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notifications
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Job - ${{ github.event.workflow_run.name }}
            Status - ${{ github.event.workflow_run.conclusion }}
            Commit - ${{ github.event.workflow_run.head_repository.html_url }}/commit/${{ github.event.workflow_run.head_commit.id }}
